ALTER TABLE public.profiles
    ADD COLUMN IF NOT EXISTS referrer_user_id UUID;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'profiles_referrer_user_id_fkey'
    ) THEN
        ALTER TABLE public.profiles
            ADD CONSTRAINT profiles_referrer_user_id_fkey
            FOREIGN KEY (referrer_user_id)
            REFERENCES public.profiles(id)
            ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS profiles_referrer_user_id_idx
    ON public.profiles(referrer_user_id)
    WHERE referrer_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.referral_commission_balances (
    user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
    balance_kobo BIGINT NOT NULL DEFAULT 0 CHECK (balance_kobo >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.referral_commission_ledger (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
    referred_user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    entry_type TEXT NOT NULL CHECK (entry_type IN ('earned', 'withdrawal')),
    amount_kobo BIGINT NOT NULL CHECK (amount_kobo > 0),
    reference TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS referral_commission_ledger_referred_user_idx
    ON public.referral_commission_ledger(referred_user_id)
    WHERE referred_user_id IS NOT NULL AND entry_type = 'earned';

CREATE INDEX IF NOT EXISTS referral_commission_ledger_user_created_idx
    ON public.referral_commission_ledger(user_id, created_at DESC);

ALTER TABLE public.referral_commission_balances ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referral_commission_ledger ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.award_referral_signup_commission(
    p_referred_user_id UUID,
    p_referral_phone TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    v_referred_profile public.profiles%ROWTYPE;
    v_referrer_id UUID;
    v_referral_digits TEXT;
    v_reference TEXT;
    v_balance_kobo BIGINT;
BEGIN
    v_referral_digits := regexp_replace(coalesce(p_referral_phone, ''), '[^0-9]', '', 'g');
    IF v_referral_digits = '' THEN
        RETURN jsonb_build_object('status', 'no_referral');
    END IF;
    IF v_referral_digits LIKE '234%' THEN
        v_referral_digits := '0' || substr(v_referral_digits, 4);
    END IF;

    SELECT * INTO v_referred_profile
    FROM public.profiles
    WHERE id = p_referred_user_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'New profile not found';
    END IF;

    IF v_referred_profile.referrer_user_id IS NOT NULL THEN
        RETURN jsonb_build_object('status', 'already_referred');
    END IF;

    SELECT id INTO v_referrer_id
    FROM public.profiles
    WHERE id <> p_referred_user_id
      AND (
        regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g') = v_referral_digits
        OR regexp_replace(coalesce(phone, ''), '[^0-9]', '', 'g') =
            CASE
                WHEN v_referral_digits LIKE '0%' THEN '234' || substr(v_referral_digits, 2)
                ELSE v_referral_digits
            END
      )
    ORDER BY created_at
    LIMIT 1;
    IF NOT FOUND THEN
        RETURN jsonb_build_object('status', 'invalid_referral');
    END IF;

    UPDATE public.profiles
    SET referrer_user_id = v_referrer_id
    WHERE id = p_referred_user_id;

    v_reference := 'referral_' || v_referrer_id::TEXT || '_' ||
        p_referred_user_id::TEXT;

    INSERT INTO public.referral_commission_balances (user_id, balance_kobo)
    VALUES (v_referrer_id, 10000)
    ON CONFLICT (user_id) DO UPDATE
    SET balance_kobo = public.referral_commission_balances.balance_kobo + 10000,
        updated_at = now()
    RETURNING balance_kobo INTO v_balance_kobo;

    INSERT INTO public.referral_commission_ledger (
        user_id, referred_user_id, entry_type, amount_kobo, reference
    )
    VALUES (
        v_referrer_id, p_referred_user_id, 'earned', 10000, v_reference
    );

    RETURN jsonb_build_object(
        'status', 'credited',
        'amount_kobo', 10000,
        'balance_kobo', v_balance_kobo
    );
END;
$function$;

CREATE OR REPLACE FUNCTION public.get_referral_summary(p_user_id UUID)
RETURNS JSONB
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
    SELECT jsonb_build_object(
        'phone', profile.phone,
        'referral_count', (
            SELECT count(*) FROM public.profiles referred
            WHERE referred.referrer_user_id = p_user_id
        ),
        'referral_earnings_kobo', coalesce((
            SELECT sum(ledger.amount_kobo)
            FROM public.referral_commission_ledger ledger
            WHERE ledger.user_id = p_user_id AND ledger.entry_type = 'earned'
        ), 0),
        'referral_commission_balance_kobo', coalesce(balance.balance_kobo, 0)
    )
    FROM public.profiles profile
    LEFT JOIN public.referral_commission_balances balance
        ON balance.user_id = profile.id
    WHERE profile.id = p_user_id;
$function$;

CREATE OR REPLACE FUNCTION public.withdraw_referral_commission(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
    v_commission public.referral_commission_balances%ROWTYPE;
    v_wallet public.wallets%ROWTYPE;
    v_amount_kobo BIGINT;
    v_balance_after BIGINT;
    v_reference TEXT;
BEGIN
    SELECT * INTO v_commission
    FROM public.referral_commission_balances
    WHERE user_id = p_user_id
    FOR UPDATE;
    v_amount_kobo := coalesce(v_commission.balance_kobo, 0);
    IF v_amount_kobo <= 0 THEN
        RAISE EXCEPTION 'No referral commission is available to withdraw';
    END IF;

    SELECT * INTO v_wallet
    FROM public.wallets
    WHERE user_id = p_user_id
    FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Wallet not found';
    END IF;

    v_balance_after := v_wallet.balance_kobo + v_amount_kobo;
    v_reference := 'commission_' || p_user_id::TEXT || '_' || gen_random_uuid()::TEXT;

    UPDATE public.wallets
    SET balance_kobo = v_balance_after, updated_at = now()
    WHERE id = v_wallet.id;

    UPDATE public.referral_commission_balances
    SET balance_kobo = 0, updated_at = now()
    WHERE user_id = p_user_id;

    INSERT INTO public.referral_commission_ledger (
        user_id, entry_type, amount_kobo, reference
    )
    VALUES (p_user_id, 'withdrawal', v_amount_kobo, v_reference);

    INSERT INTO public.wallet_ledger (
        user_id, wallet_id, entry_type, amount_kobo,
        balance_before_kobo, balance_after_kobo, description, metadata
    )
    VALUES (
        p_user_id, v_wallet.id, 'commission', v_amount_kobo,
        v_wallet.balance_kobo, v_balance_after,
        'Referral commission transferred to wallet',
        jsonb_build_object('reference', v_reference)
    );

    RETURN jsonb_build_object(
        'reference', v_reference,
        'amount_kobo', v_amount_kobo,
        'wallet_balance_kobo', v_balance_after
    );
END;
$function$;

REVOKE ALL ON FUNCTION public.award_referral_signup_commission(UUID, TEXT) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.get_referral_summary(UUID) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.withdraw_referral_commission(UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.award_referral_signup_commission(UUID, TEXT) TO service_role;
GRANT EXECUTE ON FUNCTION public.get_referral_summary(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.withdraw_referral_commission(UUID) TO service_role;
